-- =========================================================
-- DimArch OS — Hyprland v0.55+ config
-- =========================================================

-- Disable autogenerated config warning
-- hl.config({ misc = { disable_autogenerated = true } })

-- Load modules from the 'hyprland' subdirectory
require("hyprland/env")
require("hyprland/variables")
require("hyprland/input")
require("hyprland/general")
require("hyprland/colors")
require("hyprland/decoration")
require("hyprland/misc")
require("hyprland/animations")
require("hyprland/rules")
require("hyprland/keybinds")
require("hyprland/execs")

require("monitors")
